### ISSUE TITLE
Ask for usage

### ISSUE THREAD

**Issue by YeongHyeon** [bigbio/sparkms#12]
Hello, 

Thank you for providing the source code.
However, I cannot find any instructions on how to use it even in the README file.
Can I ask about the usage for utilizing this source code?

**Comment by ypriverol** [comment]
Dear @YeongHyeon Can you let us know How do you want to use the tool. You use cases. This is still under active development in PRIDE Team and we will like to know how others can use this code.

**Comment by YeongHyeon** [comment]
I forgot what I was going to use this repository for. I will contact in next time.
